### PR TITLE
fix: add check for mysql version

### LINKED ISSUE #452: Check for MySQL version on server start
Some code to help you get working:

Inside `InitDatabase()` in `MapleServer.cs` before 
```
if (DatabaseManager.DatabaseExists())
{
    Logger.Info("Database already exists.");
    return;
}
```
 just do something like 
```
if (DatabaseManager.getVersion() < MINIMUM_VERSION_HERE) {
    Logger.Error("MySQL version out-of-date, please upgrade to version " + MINIMUM_VERSION_HERE + ".");
    return;
}
```

You can check the MySQL version with something like this:
```
string connString = "server=localhost;userid=root;password=root;database=mydb";
MySqlConnection conn = new MySqlConnection(connString);

conn.Open();
Console.WriteLine("MySQL version : " + conn.ServerVersion);
```

Result:
```
MySQL version : 8.0.22
Press any key to continue . . .
```
Split the version string by a `.`, take the first number, cast it to an int, compare it with a predefined default minimum version and throw an exception if it's lower.

### PR DESCRIPTION
**Pull request by michaelowens**
Fixes #452 

Remaks:
- Is there a central place to put the required version number? Currently I put it in `InitDatabase`
- The original issue suggested returning from `InitDatabase` when the check fails. This does not stop the emulator from running. Should a shutdown be enforced or just let it crash and possibly burn?

### CODE REVIEW

File: MapleServer2/Database/DatabaseManager.cs [hunk 1]
```diff
@@ -56,6 +56,14 @@ static DatabaseManager()
 
         public static void RunQuery(string query) => new QueryFactory(new MySqlConnection(ConnectionString), new MySqlCompiler()).Statement(query);
 
+        public static int getVersion()
```
Comment (AlanMorel) [inline MapleServer2/Database/DatabaseManager.cs:59]: Should be `GetVersion`

**Review by AlanMorel — CHANGES_REQUESTED** [review]

File: MapleServer2/MapleServer.cs [hunk 2]
```diff
@@ -13,13 +13,12 @@
...
 using NLog;
 
-
 namespace MapleServer2
 {
 
     public static class MapleServer
     {
-        const int MIN_MYSQL_VERSION = 9;
+        const int MIN_MYSQL_VERSION = 8;
```
Comment (darkvergus) [inline MapleServer2/MapleServer.cs:21]: make it private

**Review by AngeloTadeucci — APPROVED** [review]

**Review by darkvergus — APPROVED** [review]

**Review by AlanMorel — APPROVED** [review]
