### PR TITLE
Fix: NpcTalkHandler

### LINKED ISSUE #313: Issues with job specific NPC dialogs
🦀 ANTI [REDACTED] SHIELD 🦀 
pls c pisscorp massage 👍 
https://discord.com/channels/783045053501276170/783051654135152640/869071093879668777

### PR DESCRIPTION
**Pull request by AngeloTadeucci**
- Created `ScriptManager` that acts as an proxy object for scripts;
- Parsing more attributes for Scripts;
- Moved `NpcTalkMode.cs` and **Scripts** to Maple2Storage;
- Added example script functions so others can also start hardcoding NPCs scripts, specially @gwagwaflamingo;
- Initial implementation of Bonus Game Handler;
- Fixed multiple things in `NpcTalkHandler` and `QuestHelper`;
- Added a bit more documentation to `NpcTalkHandler`.
- Resolves #313

### CODE REVIEW

**Comment by AngeloTadeucci** [comment]
#88

**Review by AlanMorel — APPROVED** [review]

**Review by darkvergus — APPROVED** [review]

File: Maple2Storage/Scripts/11000024.lua [hunk 1]
```diff
@@ -0,0 +1,6 @@
+function getFirstScriptId()
```
Comment (Zintixx) [inline Maple2Storage/Scripts/11000024.lua:1]: Can we have all these NPC scripts in a sub folder?

**Review by Zintixx — CHANGES_REQUESTED** [review]

**Review by Sparkymod — APPROVED** [review]

File: Maple2Storage/Scripts/11000024.lua (hunk 1 above)
Comment (AngeloTadeucci) [reply Maple2Storage/Scripts/11000024.lua:1]: Sure!

**Review by Zintixx — APPROVED** [review]

**Review by darkvergus — APPROVED** [review]
