### PR TITLE
Triggers

### LINKED ISSUE #376: Talking to Kaitlyn for mage class causes error
I get the following error when talking to Kaitlyn for the first time as a mage.

``System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=MapleServer2
  StackTrace:
   at MapleServer2.PacketHandlers.Game.NpcTalkHandler.HandleRespond(GameSession session, PacketReader packet) in C:\Users\Damien\Downloads\Maplestory 2 Server Emulator And Client\MapleServer2-master\MapleServer2\PacketHandlers\Game\NpcTalkHandler.cs:line 97``

image

### PR DESCRIPTION
**Pull request by AngeloTadeucci**
## Triggers
Added a trigger loop task in **FieldManager**;
Using portal rotation for setting the character to look at correct direction;
Handling Skip Scene;
Added `SetAnimationSequence` packet;
Added Triggers:

- DestroyNpc
- SpawnNpcRange
- MoveNpc (Waiting for Quotopia's PR with monster movement to finish this function)
- SetPcEmotionSequence
- QuestUserDetected

## InteractObject
Parsing interact object quests;
Dropping quest items when interacting with objects;

## Quests
Added **QuestState** enum;
Removed Started/Completed bool from **QuestStatus**;
Improved logic for **QuestHelper** class;

## Others
Minor logic adjustments for **NpcTalkHandler**;
Adding quests on character creation;
- Resolves #376

### CODE REVIEW

**Comment by AngeloTadeucci** [comment]
This PR also resolves

- #376

**Review by darkvergus — APPROVED** [review]

**Review by AlanMorel — APPROVED** [review]

File: MapleServer2/Triggers/TriggerConditions.cs [hunk 1]
```diff
@@ -132,28 +137,51 @@ public bool PvpZoneEnded(byte arg1)
...
     }
 
-    public bool RandomCondition(float proc, string desc)
-    {
-        Random random = new();
-        float result = (float) random.NextDouble();
-        result *= 100;
-        return result <= proc;
-    }
+    public bool RandomCondition(float proc, string desc) => RandomProvider.Get().Next(100) <= proc;
```
Comment (Zintixx) [inline MapleServer2/Triggers/TriggerConditions.cs:179]: Eventually this is going to have to be reverted out of a lambda expression when we implement the desc parameter. Is it worth having it as it is right now? dunno and prob minor. just saying

**Review by Zintixx — APPROVED** [review]

**Review by Sparkymod — APPROVED** [review]

File: MapleServer2/Triggers/TriggerConditions.cs (hunk 1 above)
Comment (AngeloTadeucci) [reply MapleServer2/Triggers/TriggerConditions.cs:179]: I'm going to leave like that, when it's needed it will be easy to fix anyway
